// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfoiqUyivT9NbZpRGq6YEwC8_FPdnG6rA',
    appId: '1:327360375655:web:8e137a20eaecbb78965dc2',
    messagingSenderId: '327360375655',
    projectId: 'agrisales-6aac2',
    authDomain: 'agrisales-6aac2.firebaseapp.com',
    storageBucket: 'agrisales-6aac2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAShZ0nU2mOFwqV3lkuFjcrjTJrZfl2JZc',
    appId: '1:327360375655:android:7cc5adae52f6f728965dc2',
    messagingSenderId: '327360375655',
    projectId: 'agrisales-6aac2',
    storageBucket: 'agrisales-6aac2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE7qcg7-77dNajChbk5ibcoDqI8OALpFw',
    appId: '1:327360375655:ios:8fb082ffee4223f9965dc2',
    messagingSenderId: '327360375655',
    projectId: 'agrisales-6aac2',
    storageBucket: 'agrisales-6aac2.appspot.com',
    iosBundleId: 'com.example.agrisale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE7qcg7-77dNajChbk5ibcoDqI8OALpFw',
    appId: '1:327360375655:ios:8fb082ffee4223f9965dc2',
    messagingSenderId: '327360375655',
    projectId: 'agrisales-6aac2',
    storageBucket: 'agrisales-6aac2.appspot.com',
    iosBundleId: 'com.example.agrisale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfoiqUyivT9NbZpRGq6YEwC8_FPdnG6rA',
    appId: '1:327360375655:web:e514d34fa5c3f3ab965dc2',
    messagingSenderId: '327360375655',
    projectId: 'agrisales-6aac2',
    authDomain: 'agrisales-6aac2.firebaseapp.com',
    storageBucket: 'agrisales-6aac2.appspot.com',
  );
}
